### PR TITLE
[INV-55] Changed page and navbar bg to gradients.

### PR DESCRIPTION
**Pull request by nskoretz**
**Baby's first gradient.**
image

- Changed the <body> background to a gradient from turquoise to dark purple
- Changed the navbar to a gradient with the same base colours, just shifted a bit darker.
- Changed background gradient angle

Please tell me what you think. I would like suggestions, although I an hesitant to play around with super bright colours.

Check out this tool, I used it to gen the gradients used. https://cssgradient.io/

It seems like you can't permalink to a specific gradient that you created, so if you come up with a desired gradient after playing around a bit, post the generated CSS in a comment.

### CODE REVIEW

**Review by DrakeEsdon — DISMISSED** [review]

**Comment by DrakeEsdon** [comment]
Looks good

**Comment by HugoKlepsch** [comment]
God damn this looks nice. Will do a full review later tonight

**Comment by nskoretz** [comment]
One thing I didn't check was how the background will look with the table on the main/home page.

We will have to probably change the tables colours and come up with another colourscheme based on the gradient, because the red theme will probably clash.

**Comment by nskoretz** [comment]
It's kind of odd. The website looks much more bright after I updated Ubuntu. Must be a new colour profile. But now I think it looks too bright? If others see it like this, should I tone it down?

Screenshot from 2019-07-17 20-27-51

**Comment by DrakeEsdon** [comment]
I feel like the color change is harsher? like the change in the bottom right feels more abrupt?

**Comment by nskoretz** [comment]
> I feel like the color change is harsher? like the change in the bottom right feels more abrupt?

Yeah I agree, like when I made the gradient I thought it went from grey-blue to grey-purple. Now its much brighter. I'll wait for @HugoKlepsch 's feedback.

**Comment by HugoKlepsch** [comment]
I actually like the brighter colors. 
I didn't get to trying any of these out last night, but we should post screenshots of a bunch of different themes before merging this. 

Main theme 1 - brighter blue:
```
background: rgb(5,0,89);
background: linear-gradient(150deg, rgba(5,0,89,1) 0%, rgba(0,142,255,0.69) 100%);
```

Nav theme 1 - Vertical fade on the navbar:
```
background: rgb(5,0,89);
background: linear-gradient(180deg, rgba(5,0,89,1) 0%, rgba(2,84,187,1) 50%, rgba(0,142,255,0.5886555305716037) 100%);
```

Main theme 2 - Grey theme if too bright:
```
background: rgb(216,216,255);
background: linear-gradient(153deg, rgba(216,216,255,1) 0%, rgba(113,151,191,1) 100%); 
```

**Comment by HugoKlepsch** [comment]
What I see checking out this branch. Investigating
image

**Comment by nskoretz** [comment]
> What I see checking out this branch. Investigating
> image

You must be a 'moz' nerd

**Comment by HugoKlepsch** [comment]
image

**Comment by HugoKlepsch** [comment]
?
image

**Comment by HugoKlepsch** [comment]
image

**Comment by HugoKlepsch** [comment]
Navbar needs to get a little darker: 
image

**Comment by nskoretz** [comment]
Looking nice

**Comment by HugoKlepsch** [comment]
Dude. 
image

**Comment by HugoKlepsch** [comment]
This is the final iteration for tonight. I would like @DrakeEsdon 's opinion too
image

**Comment by DrakeEsdon** [comment]
I like this iteration the best. The purple looks nice and the nav has a visible difference from the page.

**Review by DrakeEsdon — APPROVED** [review]

**Review by HugoKlepsch — APPROVED** [review]
I approve my own PRs now

**Comment by DrakeEsdon** [comment]
we might wanna consider this for a later sprint

`<link rel="stylesheet" href="/styles/mobile.css" media="handheld"/>`

**Pull request merged**
